### ISSUE TITLE
Wrongly configured by default

### ISSUE THREAD

**Issue by adrianmay** [complemento/docker.otrs#8]
I get this during the install.pl procedure:

Result of database check
Can't connect to database, read comment!

Can't connect to MySQL server on '127.0.0.1' (111)

**Comment by mfmatos** [comment]
Hi @adrianmay,

You do not need to access install.pl in this version. The system already performs auto configuration by simply directly accessing index.pl

Instructions for first access are here:

     Address: http://<your server address>/otrs/index.pl
     user: root@localhost
     password: ligero

**Comment by mfmatos** [comment]
Check your new version. The system already performs auto configuration by simply directly accessing index.pl

https://github.com/LigeroSmart/docker-ligerosmart

To run a stack with this new docker image, you can run simply this command:

```
  curl https://get.ligerosmart.com | sh
```

**Comment by mfmatos** [comment]
For imagem on this repository you must to run a database externally and connect to it. 

We have a complete docker-compose.yml with all services on latest version:

https://github.com/LigeroSmart/ligerosmart-stack/blob/main/docker-compose.yml
